# Generated by Django 3.1.6 on 2021-07-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('numId', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Número de indentificación')),
                ('logoProveedor', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Logo del proveedor')),
                ('nombre', models.DateField(verbose_name='Nombre de proveedor')),
                ('fono', models.CharField(max_length=12, verbose_name='Número de teléfono')),
                ('direccion', models.CharField(max_length=20, verbose_name='direccion')),
                ('region', models.CharField(max_length=20, verbose_name='Región')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('email2', models.EmailField(max_length=254, verbose_name='Reingrese su Email')),
                ('pais', models.CharField(max_length=20, verbose_name='Pais')),
                ('contrasenna', models.CharField(max_length=12, verbose_name='Contraseña')),
                ('contrasenna2', models.CharField(max_length=12, verbose_name='Reingrese su Contraseña')),
                ('moneda_pago', models.CharField(max_length=10, verbose_name='Moneda de pago: pesos/dólares')),
            ],
        ),
    ]
