# Generated by Django 3.1.6 on 2021-07-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=10, verbose_name='Nombre de proveedor'),
        ),
    ]
